"""initial schema

Revision ID: d79edea927b7
Revises:
Create Date: 2026-05-29 21:43:57.592731

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d79edea927b7"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ab_tests",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("model_a", sa.String(length=128), nullable=False),
        sa.Column("model_b", sa.String(length=128), nullable=False),
        sa.Column("traffic_b_pct", sa.Float(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=256), nullable=True),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_actor_created", "audit_logs", ["actor", "created_at"], unique=False)
    op.create_index(op.f("ix_audit_logs_created_at"), "audit_logs", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_resource", "audit_logs", ["resource_type", "resource_id"], unique=False
    )
    op.create_table(
        "drift_events",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("drift_type", sa.String(length=32), nullable=False),
        sa.Column("metric_name", sa.String(length=128), nullable=False),
        sa.Column("metric_value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("alerted", sa.Boolean(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_drift_events_detected_at"), "drift_events", ["detected_at"], unique=False
    )
    op.create_table(
        "notes",
        sa.Column("id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("patient_id", sa.String(length=256), nullable=False),
        sa.Column("encounter_id", sa.String(length=256), nullable=True),
        sa.Column(
            "note_type",
            sa.Enum(
                "progress_note",
                "discharge_summary",
                "radiology_report",
                "operative_report",
                "consultation",
                "unknown",
                name="note_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("authored_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("processed_text", sa.Text(), nullable=True),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_deidentified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_notes_patient_authored", "notes", ["patient_id", "authored_at"], unique=False
    )
    op.create_index(op.f("ix_notes_patient_id"), "notes", ["patient_id"], unique=False)
    op.create_index("ix_notes_source_type", "notes", ["source", "note_type"], unique=False)
    op.create_table(
        "embedding_records",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("note_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("model_name", sa.String(length=128), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("qdrant_collection", sa.String(length=128), nullable=False),
        sa.Column("qdrant_point_id", sa.String(length=256), nullable=False),
        sa.Column("indexed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_embedding_records_note_id"), "embedding_records", ["note_id"], unique=False
    )
    op.create_index(
        "ix_embeddings_collection", "embedding_records", ["qdrant_collection"], unique=False
    )
    op.create_index(
        "ix_embeddings_model_version",
        "embedding_records",
        ["model_name", "model_version"],
        unique=False,
    )
    op.create_table(
        "pipeline_jobs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("note_id", sa.UUID(as_uuid=False), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("stage", sa.String(length=64), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["note_id"], ["notes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_jobs_status_created", "pipeline_jobs", ["status", "created_at"], unique=False
    )
    op.create_index(op.f("ix_pipeline_jobs_note_id"), "pipeline_jobs", ["note_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pipeline_jobs_note_id"), table_name="pipeline_jobs")
    op.drop_index("ix_jobs_status_created", table_name="pipeline_jobs")
    op.drop_table("pipeline_jobs")
    op.drop_index("ix_embeddings_model_version", table_name="embedding_records")
    op.drop_index("ix_embeddings_collection", table_name="embedding_records")
    op.drop_index(op.f("ix_embedding_records_note_id"), table_name="embedding_records")
    op.drop_table("embedding_records")
    op.drop_index("ix_notes_source_type", table_name="notes")
    op.drop_index(op.f("ix_notes_patient_id"), table_name="notes")
    op.drop_index("ix_notes_patient_authored", table_name="notes")
    op.drop_table("notes")
    op.drop_index(op.f("ix_drift_events_detected_at"), table_name="drift_events")
    op.drop_table("drift_events")
    op.drop_index("ix_audit_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_created_at"), table_name="audit_logs")
    op.drop_index("ix_audit_actor_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_table("ab_tests")
    # ### end Alembic commands ###
