global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: mednlp-api
    static_configs:
      - targets: ["api:9090"]
    metrics_path: /metrics

  - job_name: mednlp-worker
    static_configs:
      - targets: ["worker-nlp:9091"]
    metrics_path: /metrics
